[package]
authors = ["Js2xxx <akucxy@163.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ferroc"
version = "0.1.0"

[features]
default = ["os-mmap"]
os-mmap = ["dep:region"]

[dependencies]
region = {version = "3.0", optional = true}

[workspace]
members = ["fuzz"]
resolver = "2"
