[package]
authors = ["Js2xxx <akucxy@163.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ferroc"
version = "0.1.0"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
base-mmap = ["dep:region"]
c = ["global", "base-mmap", "dep:libc"]
default = ["base-mmap", "global"]
global = []

[dependencies]
libc = {version = "0.2", optional = true}
region = {version = "3.0", optional = true}

[workspace]
members = ["fuzz"]
resolver = "2"
