[package]
name = "ferroc-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[[bin]]
bench = false
doc = false
name = "stress"
path = "fuzz_targets/stress.rs"
test = false

[[bin]]
bench = false
doc = false
name = "stress_local"
path = "fuzz_targets/stress_local.rs"
test = false

[[bin]]
bench = false
doc = false
name = "custom"
path = "fuzz_targets/custom.rs"
test = false

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
ctor = "1.0"
libfuzzer-sys = "0.4"
scoped-tls = "1.0"

[dependencies.ferroc]
path = ".."
