on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache fuzzing data
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-fuzz-${{ hashFiles('./fuzz/corpus/*') }}
          restore-keys: |
            ${{ runner.os }}-fuzz-
            ${{ runner.os }}-
          path: |
            ./fuzz/artifacts
            ./fuzz/corpus
            ./fuzz/coverage

      - name: Install fuzzing utilities
        run: |
          cargo install cargo-fuzz
          cargo install cargo-binutils
          cargo install rustfilt

      - name: Set up configuation
        run: |
          cp Cargo.toml Cargo.toml.bak
          cat Cargo.toml.bak | grep -v "lto" > Cargo.toml

      - name: Fuzz target
        run: |
          cargo fuzz run stress &
          PID=$!
          sleep 60
          k(){ if c=$(pgrep -P $1);then for p in $c;do k $p;done;fi;kill $1; }; k $PID
          cargo fuzz coverage stress
          cargo cov -- export -format=lcov \
            -instr-profile=./fuzz/coverage/stress/coverage.profdata \
            -object ./target/x86_64-unknown-linux-gnu/coverage/x86_64-unknown-linux-gnu/release/stress \
            -sources ./src | rustfilt > target/lcov.txt

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./target/lcov.txt
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: js2xxx/ferroc